services:
  prefect_db:
    image: postgres
    container_name: prefect_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /opt/pgdata
    user: $UID
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/opt/pgdata
      - ./prefect_db_create.sql:/docker-entrypoint-initdb.d/ddl.sql
  server:
    image: prefecthq/prefect:2.19-python3.11
    container_name: prefect_server
    depends_on:
      - prefect_db
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0 --port 4200 --ui
    volumes:
      - ./data:/opt/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      # - PREFECT_API_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////opt/data/prefect.db
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect_db:5432/prefect
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True

  worker:
    image: prefecthq/prefect:2.19-python3.11
    container_name: prefect_worker
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - EXTRA_PIP_PACKAGES=prefect-docker prefect-gitlab
      # - EXTRA_PIP_PACKAGES=prefect-docker==0.2.1 prefect-gitlab==0.2.0
    command: prefect worker start --pool wp --name stelios-worker
